### ISSUE TITLE
Undefined variables in Runtime Cache

### ISSUE THREAD

**Issue by pete-otaqui** [Anahkiasen/flatten#12]
Hi,

I'd like to base my app purely around the Runtime caching, since most of my users will be logged in and I don't want to cache all of (just about) any page.

I'm having some problems getting it running though - when I implemented it (without the blade shortcut style, just with the raw PHP call) I get an error about "undefined variables".  In this example, it's `$page` that is undefined:

    <?php Flatten::section('foo', 10, function() { ?>
        {{ $page->body }}
    <?php }); ?>

This makes sense to me, given the way variable scoping works in PHP, and that I haven't specified `use ($page)` as part of the function definition.  So I tried this:

    <?php Flatten::section('foo', 10, function() use ($page) { ?>
        {{ $page->body }}
    <?php }); ?>

But then when the cache is called, I just get an empty block back.

I'm having some trouble debugging this, so any thoughts or advice very welcome.  In general - I love the API and I really, really hope I can get this working.

Thanks for putting the time into releasing this package.

**Comment by Anahkiasen** [comment]
Will reopen if this is still happening on 1.0
