### ISSUE TITLE
Homepage cache is wrong

### ISSUE THREAD

**Issue by iGeckoDev** [Anahkiasen/flatten#25]
For some reason the cache of the homepage does not display the homepage data, instead it show displays the data of another page.  All other pages are cached properly. Any idea what might be causing this?

**Comment by Anahkiasen** [comment]
Will reopen if this is still happening on 1.0

**Comment by mattmcdonald-uk** [comment]
@Anahkiasen Yes - this is still happening on 1.0. The hash for all pages when using flatten:build is "GET-/"
