### ISSUE TITLE
Undefined Variables

### ISSUE THREAD

**Issue by angelmartz** [Anahkiasen/flatten#26]
Helo I try runtime, but on my template I get undefined variable

```php
<h1>This will not</h1>
@cache('articles', 10)
    @foreach($articles as $article)
        {{ $article->name }}
    @endforeach
@endcache

**Comment by baytbybayt** [comment]
Try echo before Flatten function:
<?php echo Flatten::section('yo_'.URL::full(), 5, function(){ ?>
            Something here
  <?php }); ?>

**Comment by Anahkiasen** [comment]
Will reopen if this is still happening on 1.0
