### ISSUE TITLE
Laravel: Way to detect if partial is cached for View Composer not making it's job useless

### ISSUE THREAD

**Issue by Namek** [Anahkiasen/flatten#30]
To prevent from composing data for already cached view I did the following workaround:

    class MenuPartialComposer {
        public function compose($view) {
            if (Cache::has('flatten-section-menu')) {
                return;
            }

            // do the rest here
        }
    }

User of Flatten shouldn't know that it uses Cache component or `flatten-section-` prefix. I believe that there should be some method in `Flatten` like `Flatten::hasCachedSection()` or whatever. Since support for Laravel sections seems to be just an addon in Flatten, I wasn't sure how to implement it the best way so I'm not proposing any commit.

**Comment by Anahkiasen** [comment]
Will reopen if this is still happening on 1.0
