### ISSUE TITLE
BuildCommand causes a segmentation fault

### ISSUE THREAD

**Issue by TheTekton** [Anahkiasen/flatten#35]
When running 'php artisan flatten:build', a segmentation fault occurs, after the last page is cached. I'm not sure what information would help track this down. This happened last night, on a BlueHost shared server, and just now on a homestead box. 

I'm just shooting in the dark here, but I'm assuming it may have to do with the CrawlPages recursion code. When building a cache with 103 pages that get queued, a error occurs if xdebug is enabled, saying that the maximum nesting level was exceeded (defaults to 100, I had it set to 200). Also, there are a few 404 errors, from a few pages that have links, but don't yet exist. (Those 404s are the only errors I see in laravel.log.)

If I'm asked to, when I find time, I can help try to find the root-cause.

**Comment by Anahkiasen** [comment]
Will reopen if this is still happening on 1.0
