### ISSUE TITLE
Kickstart duplicates query string

### ISSUE THREAD

**Issue by carlosvini** [Anahkiasen/flatten#40]
Kickstart uses REQUEST_URI and QUERY_STRING to make its $key. The problem is that most servers i know already have the query string in REQUEST_URI, so the key gets a duplicated query string.

Line 130: https://github.com/Anahkiasen/flatten/blob/master/src/Flatten/Flatten.php#L130

You can replace it with something like parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)

**Comment by Anahkiasen** [comment]
Will add a way to override the default saltshaker in kickstart
