### ISSUE TITLE
Add Cached-by Meta

### ISSUE THREAD

**Issue by thiagof** [Anahkiasen/flatten#41]
In order to debug caching would be nice to have a header or a html comment in the output

**Comment by gritdigital-mibu** [comment]
I think this functionality already exists, or at least it does in the versions I've used.

You should see  "" at the very bottom of your HTML.

**Comment by Anahkiasen** [comment]
As @gritdigital-mibu said it should [already be the case](https://github.com/Anahkiasen/flatten/blob/master/src/Flatten/CacheHandler.php#L84)

**Comment by thiagof** [comment]
True, I have missguided it
