### ISSUE TITLE
Dependencies could not be resolved?

### ISSUE THREAD

**Issue by gritdigital-mibu** [Anahkiasen/flatten#42]
flatten/composer.json `"illuminate/contracts": "5.0.|5.1.*"`

![composer-flatten](https://cloud.githubusercontent.com/assets/11611416/9760694/51174048-56ef-11e5-816d-964ff35a261a.png)

`5.0.*` ?

**Comment by Anahkiasen** [comment]
Wow, don't know how that got past me. Guessing Composer ignored the invalid constraint as I was installing it on a 5.1 app. Will push a fix soon

**Comment by Anahkiasen** [comment]
Tagged 1.0.2 with the fixed constraint
